### ISSUE TITLE
Button Colors not showing in 2.4.0

### ISSUE THREAD

**Issue by vincentliu98** [duytq94/flutter-intro-slider#106]
I upgraded the package from 2.3.3 to 2.4.0 after upgrading my Flutter project to Flutter 2. However, the colors of buttons in the bottom disappeared, despite I specified colors as below:

```  
      colorSkipBtn: darkGreen,
      colorDoneBtn: darkGreen,
```
![Screenshot_1619126821](https://user-images.githubusercontent.com/25229705/115787972-f8d10c80-a390-11eb-9a9c-3110d5b96b09.png)

I think the cause is using TextButton's `primary` parameter instead of `backgroundColor`. After modifying the package on my end and testing it out, I was able to restore the button colors.

![Screenshot_1619126969](https://user-images.githubusercontent.com/25229705/115788095-2cac3200-a391-11eb-9691-ae47b07633ea.png)

Also, in 2.4.0, `highlightColorSkipBtn` and `highlightColorDoneBtn` are not used in TextButton. Can they be added to reproduce the effect from 2.3.3?

Thanks.

**Comment by duytq94** [comment]
Thanks for your report 💯 
Fixed immediately here https://github.com/duytq94/flutter-intro-slider/releases/tag/2.4.1
