### ISSUE TITLE
onTabChangeCompleted is never called

### ISSUE THREAD

**Issue by Okiring** [duytq94/flutter-intro-slider#107]
![Screen Shot 2021-05-07 at 12 49 08 PM](https://user-images.githubusercontent.com/27002476/117432077-9fd9aa80-af32-11eb-84ac-79bcfa7027a5.png)

**Comment by duytq94** [comment]
OK, I got it, missing it when migrating, I'm adding it.
If you got any misses, please tell me.

**Comment by festapp86** [comment]
Yes, we have the same issue, the method onTabChangeCompleted is never called. Please be so kind and provide the fix. Highly appreciated

**Comment by duytq94** [comment]
Fixed at https://github.com/duytq94/flutter-intro-slider/releases/tag/2.4.2
