### ISSUE TITLE
backgroundColorAllSlides not working

### ISSUE THREAD

**Issue by subzero911** [duytq94/flutter-intro-slider#109]
set `backgroundColorAllSlides: dustyRoseColor`
expected behaviou - background of all slides changed
actual behaviour - background remains default yellow
but it works if I manually set `backgroundColor: dustyRoseColor` for each Slide

**Comment by duytq94** [comment]
Hi,
`backgroundColor` for each slide is higher prior than`backgroundColorAllSlides`, so please disable `backgroundColor` in each slide to make `backgroundColorAllSlides` effect to it.
Thanks.
