### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by subzero911** [duytq94/flutter-intro-slider#110]
I change a button to something custom:
```dart
renderSkipBtn: Text(
        'very long text',
        softWrap: false,
        overflow: TextOverflow.visible,
        style: Theme.of(context).textTheme.button,
      ),
```
expected behaviour: SkipButton immediately changed after file saving
actual behaviour: SkipButton remains unchanged until I reopen Intro screen. It makes debugging harsh.

**Comment by duytq94** [comment]
Already exist here https://github.com/duytq94/flutter-intro-slider/issues/59
At the moment I haven't had time to deep dive into it, so if you have any suggestion, please tell us.
