### ISSUE TITLE
[Feature request] Horizontal layout

### ISSUE THREAD

**Issue by marchellodev** [duytq94/flutter-intro-slider#112]
As of right now, it is impossible to use this package on horizontal screens (or in a landscape mode). It would help if we could specify the type of layout: vertical (as it is right now) or horizontal (when image, and description are located in a row)
Thanks!

**Comment by duytq94** [comment]
Hi, sorry for late.
You can using https://github.com/duytq94/flutter-intro-slider#custom-layout to layout your widget position
