### ISSUE TITLE
Multiple Instance

### ISSUE THREAD

**Issue by LiveRock** [duytq94/flutter-intro-slider#114]
Hi
I am using intro-slider as HELP Pages and it is used in different sections.
I realised that when I navigate between sections, intro-slider still show old content even thru they are instantiated in different classes.
How do I mitigate this?
Thanks and hope to hear from you soon.

**Comment by duytq94** [comment]
I tested with this case (intro 1 => home => intro2) and it works normally, can you explain in more detail your case?
![ezgif com-gif-maker](https://user-images.githubusercontent.com/24253421/122708127-a3788500-d285-11eb-80ab-cd3194f82ac8.gif)

**Comment by LiveRock** [comment]
I mean I have 4 instances of intro-slider with all different content pages

**Comment by duytq94** [comment]
Can you give your code example? I tested with different pages and it's work normally.
