### ISSUE TITLE
Buttons not clickable because of missing SafeArea

### ISSUE THREAD

**Issue by novas1r1** [duytq94/flutter-intro-slider#122]
Hey, 
I have a huge problem with my Pixel 4a. The android buttons are overlaying the Slider buttons which makes it unusable atm because I can't finish the Intro. Is there any solution to move the buttons up? I'm tried wrapping it into SafeArea but it didn't work.

![WhatsApp Image 2022-02-24 at 11 16 12](https://user-images.githubusercontent.com/2575205/155505259-2b93a920-4885-42e0-aae8-79a91f12c36b.jpeg)

Best regards
Verry

**Comment by duytq94** [comment]
Hi @novas1r1 , just because I'm setting full screen for the default.
You can solve by using `hideStatusBar: false`

![Screen Shot 2022-03-18 at 9 52 32 PM](https://user-images.githubusercontent.com/24253421/159026059-6897af4d-0f23-4d1d-bc9a-ca6927a35a2b.png)
