### ISSUE TITLE
Background color amber when not set

### ISSUE THREAD

**Issue by Fintasys** [duytq94/flutter-intro-slider#126]
Hey!
I saw that you made a change in previous version to set background color to amber when not set
https://github.com/duytq94/flutter-intro-slider/commit/24073edfe91494a3959c51e2d592151c1b64f308
Unfortunately when I set no background color on each slide, the background color will be `amber` even when I set `backgroundColorAllSlides` which makes this attribute meaningless. 

Beside that awesome library and became much better since I used it last time :)

**Comment by duytq94** [comment]
Hi,
Thanks for your report, it's really a bug, I fixed it at https://github.com/duytq94/flutter-intro-slider/commit/f4177afa58bbcc06c3fc471ae8e684040c86550b#diff-c5dfc6e26d4b0d16d3f66208985ddf6b0409ff60c94f6947db02f7a39a2159f0
