### ISSUE TITLE
Move background image to position

### ISSUE THREAD

**Issue by MTRNord** [duytq94/flutter-intro-slider#13]
Hi how could I move the bg image to a specific position? 

Basicly like the rocket in this image. (Dont mind the blured text)

![grafik](https://user-images.githubusercontent.com/1374914/53906616-b383e080-404b-11e9-8fd8-f9706ebe824d.png)

**Comment by duytq94** [comment]
Hi,
Let's try centerWidget and pass your custom widget. Thanks.
