### ISSUE TITLE
Buttons text color

### ISSUE THREAD

**Issue by cksrc** [duytq94/flutter-intro-slider#130]
I was not able to change the font color of the skip,next,done buttons.
None of the below seem to affect the color which looks to be overridden by white color.

``` ButtonStyle myButtonStyle() {
      return ButtonStyle(
      textStyle: MaterialStateProperty.all<TextStyle>(
          const TextStyle(color: Color(0xFF2D2D2D))),
      shape: MaterialStateProperty.all<OutlinedBorder>(const StadiumBorder()),
      backgroundColor:
          MaterialStateProperty.all<Color>(const Color(0xFFC0DBCD)),
      overlayColor: MaterialStateProperty.all<Color>(const Color(0xFF2D2D2D)),
    );
  }
```

Please note I was able to alter other button styling properties, but not the text color.

**Comment by duytq94** [comment]
Fixed in https://github.com/duytq94/flutter-intro-slider/pull/132
