### ISSUE TITLE
Example of refFuncGoToTab

### ISSUE THREAD

**Issue by Lirry18** [duytq94/flutter-intro-slider#137]
Hi @duytq94 !

Great package so far! I am just confused how to implement programmatically changing the tabs. I saw you have the  refFuncGoToTab function. Right now I want to test that if some condition is met, we will go to the next slide.

In my view:
```
`@override
  Widget build(BuildContext context) {
    return IntroSlider(
      scrollable: false,
      slides: controller.slides,
      onDonePress: controller.onDonePress,
      onTabChangeCompleted: controller.tabChanged,
      refFuncGoToTab: controller.goToNext,
    );
  }`
```

In my controller:
```
  void goToNext(Function goToTab) {
    if(currentIndex == 1 && firstStepSuccess == true){
      goToTab(2);
    }
  }
```

Then when something was met I called:
`tutorialController.goToNext(()=> 2);`

Which doesnt work. I am a bit confused of the Function inside of the function. I have implemented onTabChangeCompleted fine so thats why im confused this is different.

**Comment by duytq94** [comment]
Hi, you can check https://github.com/duytq94/flutter-intro-slider#custom-layout, code example section
Define: `late Function goToTab;`
Set ref: `refFuncGoToTab: (refFunc) {
        goToTab = refFunc;
      },`
Invoke: `goToTab(0);` => then it will jump to first tab (index 0)
