### ISSUE TITLE
can't change inActive indicator dots colors

### ISSUE THREAD

**Issue by heshesh2010** [duytq94/flutter-intro-slider#141]
Hi , 
I have set the colors for orange and black as my code shows , but I see only orange color is set on selected dot (active dot) and also inActive dots 

```
                  indicatorConfig: IndicatorConfig(
                    activeIndicatorWidget: Container(
                      width: 10.0,
                      height: 10,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(4),
                        color: Colors.black,
                      ),
                    ),
                    indicatorWidget: Container(
                      width: 10.0,
                      height: 10,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(4),
                        color: AppColors().mainColor(1),
                      ),
                    ),
                    isShowIndicator: true,
                    spaceBetweenIndicator: 10.0,
                    typeIndicatorAnimation:
                        TypeIndicatorAnimation.sizeTransition,
                  ),


```

![Screenshot 2023-08-29 at 1 12 29 AM](https://github.com/duytq94/flutter-intro-slider/assets/16393042/e4af18be-bae5-46fe-b984-c50d4d6e0293)

**Comment by duytq94** [comment]
Hi, sorry for late reply.
This is the current limit I mentioned in readme
![Screenshot 2023-09-09 at 10 34 09](https://github.com/duytq94/flutter-intro-slider/assets/24253421/980d2b15-bd64-45a5-94f8-6ec7fa98435f)

**Comment by duytq94** [comment]
Hi, sorry for late replay,
You are using **TypeIndicatorAnimation.sizeTransition**, which is generally understood as changing the size of the widget.
In your case define both active and non-active indicators, so if the active is a circle and the non-active is a square, how does the animation look like, right?
So this is the limitation I mentioned here:
![Screenshot 2023-09-09 at 10 34 09](https://github.com/duytq94/flutter-intro-slider/assets/24253421/6461902b-b3b3-48ab-9256-c3bbf9f812d1)

**Comment by duytq94** [comment]
I just updated (the latest version lib at this time ~ 4.2.1) to make it able to use **colorActiveIndicator** when using **TypeIndicatorAnimation.sizeTransition** (without using custom indicator case), like this
```
indicatorConfig: const IndicatorConfig(
  colorIndicator: Colors.orange,
  colorActiveIndicator: Colors.black,
  sizeIndicator: 13.0,
  typeIndicatorAnimation: TypeIndicatorAnimation.sizeTransition,
),
```
![Simulator Screen Shot - iPhone 13 - 2023-09-09 at 13 09 04](https://github.com/duytq94/flutter-intro-slider/assets/24253421/313ac68c-3ddf-419e-9140-e446cc0c2fc1)

Hoping can help.
