### ISSUE TITLE
Implementation for onSkipPress

### ISSUE THREAD

**Issue by Purus** [duytq94/flutter-intro-slider#15]
What is the default implementeation of onSkipPress action? I could not find any example of moving to the last slide when the skip button is pressed..

It would be good idea to provide a defaul implementation.

**Comment by duytq94** [comment]
Thanks for your report, I fixed at
[https://github.com/duytq94/flutter-intro-slider/commit/e9c7bfc136ca19c4fadf555d60eaacc8f52426ff](url)

**Comment by Purus** [comment]
Thank you 💯
