### ISSUE TITLE
Make compatible with hot reload

### ISSUE THREAD

**Issue by James-A-White** [duytq94/flutter-intro-slider#18]
Wonderful package!  Would be even better if Flutter's hot reload feature could be used when designing slides.  I've tried several ways to do this, including re-creating the intro slider completely, but nothing seems to work. Is there a way for me to code this up? Or, if not, is it possible to add a refresh method to the IntroSlider class that would cause the slider to reload all of the slides?

Many thanks!

**Comment by James-A-White** [comment]
Actually, I just solved my issue...  Instead of trying to change the state and reload elements on the page. I simply use the Navigator and push the page as its own replacement.

     Navigator.of(context)
                  .pushReplacementNamed(RouteNames.INTRO_SLIDER.toString());

This causes the entire page to reload and redraws all of the slides. It's a bit of a hack, but it works.

**Comment by j3g** [comment]
Hi James, did this work because you defined routes in your MaterialApp()? I am having trouble with the Navigator.pop() command giving me a black screen so I'm curious how your routes are setup. Thank you.
