### ISSUE TITLE
onSkipPress method withdrawn in latest version

### ISSUE THREAD

**Issue by devmanjun** [duytq94/flutter-intro-slider#19]
Greetings!
I was using the version 1.1.9 where I had controls for both onSkipPress and onDonePress, which was exactly what I required. In the latest version 1.2.0, the onSkipPress method is taken out and I couldn't find a way to customize it. The default implementation of onSkipPress is not what I'm looking for.
I would like to have the onSkipPress method back. Please let me know if there are any other ways to customize it.

**Comment by duytq94** [comment]
Hi @devmanjun 
My mistake, I brought it back in version 1.2.1.
Thanks.

**Comment by devmanjun** [comment]
Thank you
