### ISSUE TITLE
On pressed trigger on the slide

### ISSUE THREAD

**Issue by natarajnattu** [duytq94/flutter-intro-slider#2]
Is there any way to implement onclick on the image or slide

slides.add(
      new Slide(
        title: "Title of the page",
        description: "Description of the page",
        backgroundColor: 0xFF0093FF,
      ),
      **onClick: doSomething();**
    );

**Comment by duytq94** [comment]
Hi @natarajnattu , sorry for late. Ok, I'll add this feature in next version. Thanks.

**Comment by duytq94** [comment]
Hi @natarajnattu ,
I add this feature, please check out the latest version.

**Comment by natarajnattu** [comment]
Thanks much @duytq94
