### ISSUE TITLE
请问背景图可以支持NetWorkImage吗

### ISSUE THREAD

**Issue by FrankKong** [duytq94/flutter-intro-slider#21]
请问背景图可以支持NetWorkImage吗

**Comment by duytq94** [comment]
Hi @FrankKong 
The `Image` attribute at Slide object does not support network, but you can use `centerWidget` and push your own NetworkImage widget

![Capture](https://user-images.githubusercontent.com/24253421/57508192-0cf9db80-732b-11e9-90cf-2c673c033c87.PNG)
