### ISSUE TITLE
i am not able to set Slide in this Order (Image - Title - Description)

### ISSUE THREAD

**Issue by Harishpenta** [duytq94/flutter-intro-slider#22]
i want to sent the slide page in the following order
Image - Title - Description

how to make it so.?

**Comment by duytq94** [comment]
Hi @Harishpenta 
Currently, we can't do this thing. I will upgrade to help user custom UI and order items entire slide.

**Comment by duytq94** [comment]
@Harishpenta 
d363cba1eb17816bf0b4d6d598aba19cb0422930
I just add this feature on version 2.0.0, please checkout readme for more info.
