### ISSUE TITLE
Error in 2nd time

### ISSUE THREAD

**Issue by ziasultan2** [duytq94/flutter-intro-slider#23]
I install and used this plugin yesterday and it works fine. But today when I run it says
* What went wrong:
A problem occurred configuring project ':intro_slider'.
> Could not resolve all dependencies for configuration ':intro_slider:classpath'.
   > Could not load module metadata from C:\Users\emonh\.gradle\caches\modules-2\metadata-2.63\descriptors\com.android.tools.build\gradle\3.0.1\6740fe48b44caed96d7f50b66ff7b0b5\descriptor.bin
Same thing happens earlier. I thought maybe there is some mistake. So I create new project but same error again after restart computer

Here is my code

import 'package:flutter/material.dart';
import 'package:intro_slider/intro_slider.dart';
import 'package:flutter_login/ui/login.dart';

class IntroScreen extends StatefulWidget {
  IntroScreen({Key key, this.title}) : super(key: key);

  final String title;

  @override
  IntroScreenState createState() => IntroScreenState();
}

class IntroScreenState extends State<IntroScreen> {

  List<Slide> slides = new List();

  @override
  void initState() {
    super.initState();

    slides.add(
      new Slide(
        title: "ERASER",
        description: "Allow miles wound place the leave had. To sitting subject no improve studied limited",
        pathImage: "images/eraser.png",
        backgroundColor: Color(0xfff5a623),
      ),
    );
    slides.add(
      new Slide(
        title: "PENCIL",
        description: "Ye indulgence unreserved connection alteration appearance",
        pathImage: "images/pencil.png",
        backgroundColor: Color(0xff203152),
      ),
    );
    slides.add(
      new Slide(
        title: "RULER",
        description:
        "Much evil soon high in hope do view. Out may few northward believing attempted. Yet timed being songs marry one defer men our. Although finished blessing do of",
        pathImage: "images/ruler.png",
        backgroundColor: Color(0xff9932CC),
      ),
    );
  }// End of Init sTATE

  void onDonePress()
  {
    Login(title: 'Layzey Intro Screen');
  }// End of onDonePress

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return  new IntroSlider(
      slides: this.slides,
      onDonePress: this.onDonePress,
    );
  }

}

**Comment by duytq94** [comment]
Hi @ziasultan2 ,
I just checking with init new project, nothing wrong happens, maybe you try to check and update your gradle or other relevant.
https://stackoverflow.com/questions/35705698/error-loading-project-in-android-studio-cannot-load-modules/35706123
https://github.com/googlesamples/android-architecture-components/issues/277

**Comment by ziasultan2** [comment]
it's giving me error when I run after install it.
