### ISSUE TITLE
How to set image to full width?

### ISSUE THREAD

**Issue by momsenmeister** [duytq94/flutter-intro-slider#24]
Hi,
I want to give a foreground image in the slide the full width of the viewport.

The original image size is 1500 x 2200.
I tried to set
`widthImage: 1500,`
but the image stays very small in the center, it doesn't stretch to full width.

When I also set a `heightImage`, the image stretches. 
But I just want to give it the full width.
Something like `foregroundImageFit: BoxFit.contain` would be great!

How can I do this?

Thanks,
Michael

**Comment by duytq94** [comment]
Hi @momsenmeister 

First, the widthImage and heightImage is not the resolution of the picture (Eg: my phone is FullHD 1920x1080 => 640x360 <- use these number) so you set width = 1500 seem not true, you can use MediaQuery.of(context).size.width to calculate your device.

Second, I set `fit: BoxFit.contain` in the lib's source code
![image](https://user-images.githubusercontent.com/24253421/57861502-ece18500-7820-11e9-9aee-6549c0cd0788.png)
![image](https://user-images.githubusercontent.com/24253421/57861473-e18e5980-7820-11e9-8d90-60ba67cb08ed.png)

Third, and follow flutter instructions, you should:
> It is strongly recommended that either both the width and the height be specified


So you should specify both width and height, your image is 1500x2200 means width = 1500 and height = 2200, right? And assume that your device is FullHD, if you set width = 360 (to full-width screen device), the height if keep the ratio origin image should be 528.
And the result will like this:
![ezgif-1-1d8969e5621e](https://user-images.githubusercontent.com/24253421/57863484-629b2000-7824-11e9-8950-2d548538ea00.gif)

Let me know if it can help you.
Thanks!

**Comment by duytq94** [comment]
I'll close this issues since it depends on your code config, not the plugin.
Btw, feel free to keep discussing.

**Comment by momsenmeister** [comment]
Thanks!
I switched to `centerImage` instead of using `pathImage`, which seems to do exactly, what I need, without configuration of the width or height.
I didn't manage to get the proper result with your instructions, the image always stayed small or scaled with undesired behaviour when I also set the height.

**Comment by hufu4635** [comment]
Have you solved this problem?
 I want to set up a full screen picture. 
But it didn't work.
Can you tell me how to solve it?

**Comment by khalidabdou** [comment]
please set this  viewportFraction: 1.0,

**Comment by khalidabdou** [comment]
please set this viewportFraction: 1.0, @hufu4635 @momsenmeister
