### ISSUE TITLE
Access to active tab index

### ISSUE THREAD

**Issue by khalilst** [duytq94/flutter-intro-slider#25]
Hello. Thx for your great package.
It could be nice if there a way to access the **Active Tab Index**.
For example pass it to renderNextBtn and other render stuffs.
This is my scenario for this feature.
I want to **enable/disable** the `isShowDotIndicator`.

**Comment by duytq94** [comment]
Hi @khalilst 
I added in latest version (2.0.2)
![image](https://user-images.githubusercontent.com/24253421/58364225-3003be00-7edb-11e9-863e-2e0de5f96771.png)
Checkout example to know how to use it.
