### ISSUE TITLE
NoSuchMethodError was thrown while dispatching notifications for TabController

### ISSUE THREAD

**Issue by chabislav** [duytq94/flutter-intro-slider#26]
`I/flutter (17897): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (17897): The following NoSuchMethodError was thrown while dispatching notifications for TabController:
I/flutter (17897): The method 'call' was called on null.
I/flutter (17897): Receiver: null
I/flutter (17897): Tried calling: call(1)
I/flutter (17897): 
I/flutter (17897): When the exception was thrown, this was the stack:
I/flutter (17897): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (17897): #1      IntroSliderState.initState.<anonymous closure> (package:intro_slider/intro_slider.dart:426:12)
I/flutter (17897): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
I/flutter (17897): #3      TabController._changeIndex (package:flutter/src/material/tab_controller.dart:131:7)
I/flutter (17897): #4      TabController.index= (package:flutter/src/material/tab_controller.dart:146:5)
I/flutter (17897): #5      _TabBarViewState._handleScrollNotification (package:flutter/src/material/tabs.dart:1246:21)
I/flutter (17897): #6      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:127:27)
I/flutter (17897): #7      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
I/flutter (17897): #8      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
I/flutter (17897): #9      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3355:39)
I/flutter (17897): #10     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:61:13)
I/flutter (17897): #11     ScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:96:92)
I/flutter (17897): #12     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:658:14)
I/flutter (17897): #13     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:219:9)
I/flutter (17897): #14     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:84:18)
I/flutter (17897): #15     BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:547:21)
I/flutter (17897): #16     BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:534:10)
I/flutter (17897): #17     _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:126:19)
I/flutter (17897): #18     AnimationController._tick (package:flutter/src/animation/animation_controller.dart:750:5)
I/flutter (17897): #19     Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
I/flutter (17897): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (17897): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:928:11)
I/flutter (17897): #22     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
I/flutter (17897): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:926:17)
I/flutter (17897): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:856:5)
I/flutter (17897): #28     _invoke1 (dart:ui/hooks.dart:233:10)
I/flutter (17897): #29     _beginFrame (dart:ui/hooks.dart:172:3)
I/flutter (17897): (elided 3 frames from package dart:async)
I/flutter (17897): 
I/flutter (17897): The TabController sending notification was:
I/flutter (17897):   Instance of 'TabController'
I/flutter (17897): ════════════════════════════════════════════════════════════════════════════════════════════════════
`

looks like 2.0.2 throws this error on swipe.

**Comment by duytq94** [comment]
Thanks for your report @chabislav 
I forgot check null when onTabChangeCompleted not defined, fixed in 2.0.3
