### ISSUE TITLE
Remove Done and Next button

### ISSUE THREAD

**Issue by pascalf22** [duytq94/flutter-intro-slider#27]
Hello ! Flutter-intro-slider is perfect. But i need to delete the DONE button and the NEXT button..

I see that i can hide the PREV button and SKIP button with isShowSkipBtn and isShowPrevButton..

But there is nothing to hide Done and Next button.

How can i do it ?

Thanks a lot !
Pascal

**Comment by duytq94** [comment]
Hi @pascalf22 
I add an attribute to hide it, please checkout 2a59f44e1f3d5a0d0c6cfd45155f1686618cabe7

**Comment by pascalf22** [comment]
Hello @duytq94 !! That  Wonderful !!

Thanks a lot for your help !!
Have a great day !

Pascal
