### ISSUE TITLE
RouteTRansition doesn't work if second page has a IntroSlider

### ISSUE THREAD

**Issue by pascalf22** [duytq94/flutter-intro-slider#29]
Hello @duytq94  !

Thanks for Flutter-intro-slider, i love it !

I have one more issue...

I have 2 pages. When i go to the second page, i added a route Transition(left to right transition), the second page has the flutter-intro-slider.

The transition doesn't work if there is the flutter-intro-slider in the page.
If i comment the intro-slider, the transition works perfectly... but not with the flutter-intro-slider.

Do you know why ? How can we solve this issue ?

Thanks a lot and have a great day ! 

Pascal

**Comment by duytq94** [comment]
Hi @pascalf22 
I tested with your case, page 1 -> page 2 with left-to-right transition, the transition works fine.
![ezgif com-resize](https://user-images.githubusercontent.com/24253421/59005495-f79fa080-8847-11e9-9749-f95efcffe32a.gif)

**Comment by pascalf22** [comment]
Hello @duytq94 ,
Ok thanks ! I will check it again ! I don't understand why ?? But i will check it again
Thanks a lot !! 

Pascal

**Comment by duytq94** [comment]
#31
