### ISSUE TITLE
Suggestion: color options to be instances of `Color` rather than `int`

### ISSUE THREAD

**Issue by jacobimpson** [duytq94/flutter-intro-slider#3]
Great package! 
I would however suggest that perhaps instead of using `int`s for color config, you use `Colour` instances directly. This would bring it inline with Flutter's inbuilt widgets. Eg.

Flutter's app bar..
```
AppBar(
 backgroundColor: Colors.white
 [....]
)
```

Changing to using colors like this will more easily allow for colors to be pulled out of the App's theme object. I would be happy to make this change if it's a direction that you're happy with.

**Comment by duytq94** [comment]
Hi @jacobimpson 
OK, that's a good idea, I'll update it.
Thanks.

**Comment by duytq94** [comment]
Updated.

**Comment by kalkotekedar** [comment]
I can't use Colors.white for text style. I have to use the colour in the Color(0xFFF44336) format only.

**Comment by duytq94** [comment]
@kalkotekedar 
Did you install the latest version?
If you did it. Where exactly you can't use Colors.white? Actually Colors.white is the same type Color(0xFFFFFF) so I don't understand how you can't use it.
Please post more detail about the error.

**Comment by kalkotekedar** [comment]
`styleTitle: TextStyle(
          color: PrimaryColor,
          fontSize: 30.0,
          fontWeight: FontWeight.bold,
          fontFamily: UIData.quickFont),
      `
Here if I enter use the constant color like thw following is not working
`const PrimaryColor = const Color(0xF44336);`

**Comment by duytq94** [comment]
![image](https://user-images.githubusercontent.com/24253421/52829012-b00cd180-30fd-11e9-9b8b-7130b3dea6ab.png)
I checked it again and nothing wrong, if you use exactly `0xF44336` maybe you miss FF prefix.

**Comment by kalkotekedar** [comment]
Do I need to add the FF prefix??

**Comment by duytq94** [comment]
Why you don't need? First 2-prefix is opacity, you don't use mean your opacity is 100% and of course, nothing show because it's transparent.

**Comment by kalkotekedar** [comment]
Ok, Thank You !!!
