### ISSUE TITLE
Color dots displaced to the right on last slide

### ISSUE THREAD

**Issue by arunabhCronJ** [duytq94/flutter-intro-slider#32]
The colored dots for the slider displace/slide to the right by few pixels on the last slide.
Issue replicable on emulator as well as physical device.
Issue is independent of the number of slides. Displacement occurs only on the last slide.

**Comment by duytq94** [comment]
Can you give me a screenshot?

**Comment by arunabhCronJ** [comment]
Have a look at slide 2 and 3. The colored dots are dispalced by few pixels to the right on slide 3.
Had to hide the logo because of confidentiality reasons.

![slide 3](https://user-images.githubusercontent.com/49940233/59145457-d97da000-8a01-11e9-9ceb-a2ef51aa3106.png)
![slide 2](https://user-images.githubusercontent.com/49940233/59145458-d97da000-8a01-11e9-90ab-7d058bf45865.png)

**Comment by duytq94** [comment]
I got it, let me check.

**Comment by duytq94** [comment]
Fixed at f3adabfd7692dced15b042b5e4bdd27ee3698257
Please pull the latest version (2.2.1)
Thanks for your report

**Comment by arunabhCronJ** [comment]
Works like a charm now.
Thank you.
