### ISSUE TITLE
Adjust dots with flutter_localizations direction

### ISSUE THREAD

**Issue by rami-alloush** [duytq94/flutter-intro-slider#33]
I'm building an Arabic App (right to left direction). Everything works fine except for the dot indicator it keeps going from Left to Right.
Thanks

**Comment by duytq94** [comment]
Hi @rami-alloush 
Do you know any method at flutter to detect which direction is using? If it does, I can auto detect and set the right direction.
If not, maybe I give an attribute as an option to set direction.

**Comment by rami-alloush** [comment]
Thanks @duytq94 for the reply.
`GlobalWidgetsLocalizations.delegate` defines the default text direction, either left to right or right to left, for the widgets library.
Please refer to this page for more details [here](https://flutter.dev/docs/development/accessibility-and-localization/internationalization)

**Comment by duytq94** [comment]
Thanks @rami-alloush 
But what I really need is there any method that help us **detect which direction is using**. And seem your advice does not mention about it.

**Comment by rami-alloush** [comment]
There are only 5 languages that are RTL.
You can check and detect them. Please refer to this answer [https://stackoverflow.com/a/54689825/4157431](url)
Thanks

**Comment by duytq94** [comment]
I'm fixed in 2.2.3 with df49af8b332425df45ff51d9b15be7bc099128b3
Thanks for your suggestion.

**Comment by xmavara** [comment]
it does not work well yet, please fix it. everything is fine except for dots in rtl Directionality.

**Comment by duytq94** [comment]
@xmavara please read here https://github.com/duytq94/flutter-intro-slider/issues/20

**Comment by AlaaMarawi** [comment]
@duytq94 can you please at least wrap it with Directionality widget which is LTR by default but can be RTL by user choice ?
it should be very easy ..
thank you for this amazing plugin :)
