### ISSUE TITLE
Undefined name 'Slide'

### ISSUE THREAD

**Issue by ajaymakhecha** [duytq94/flutter-intro-slider#35]
![erre](https://user-images.githubusercontent.com/50327505/60399337-a94c9b80-9b80-11e9-86d2-180502681f0a.png)
Whenever I create a slide I'm getting this error.

**Comment by duytq94** [comment]
Hi, you forgot a simple operation that import it.
![Capture](https://user-images.githubusercontent.com/24253421/60406051-307c2c80-9bde-11e9-84ac-a8532cdd996a.PNG)
