### ISSUE TITLE
centerWidget not loading Android release mode

### ISSUE THREAD

**Issue by bremington** [duytq94/flutter-intro-slider#40]
hi, my app works great in debug/release mode for iOS, and debug mode for Android. It uses a centerWidget for my slides using intro-slider. However, when I build in release mode for Android and load on a device, the centerWidget is blank. If I restart the app, after the initial install, it then shows the centerWidget. I am using the latest Gradle (3.5.0)

**Comment by duytq94** [comment]
Hi, what exactly centerWidget you're using? Maybe your widget is too heavy for render?
I tested with a fresh project by text or image in centerWidget, it works fine in Android release mode.
Trying your widget with the new project and tell me the result.

**Comment by bremington** [comment]
Hi Duy,

So I use two different centerWidgets..on my first 4 slides I use a simple 200x200px image (image.asset). On my 5th slide I use a Step widget. None are shown on initial build. However, if I add a restart of the program, after a 1 sec delay, I can show the centerWidget for Android release. So not sure if the 5th usage building a Step widget stops all centerWidgets from being built.

**Comment by duytq94** [comment]
I don't know exactly Step widget which the 5th slide contains as you said. Can you try without this slide?
I tested with 5 slides, each slide has a custom widget which contains an image with 512 x 512px and nothing wrong happen.
