### ISSUE TITLE
How to jump to the specified index tab at the beginning

### ISSUE THREAD

**Issue by SteveSuv** [duytq94/flutter-intro-slider#42]
For example, there are a total of 5 slides. I want to display the 3rd page when I open this page, and the dot below also shows the 3rd highlight.

**Comment by duytq94** [comment]
Hi, you can use `refFuncGoToTab ` like this
```
refFuncGoToTab: (refFunc) {
    this.goToTab = refFunc;
    // tab index to jump at first loading
    refFunc(2);
},
```
