### ISSUE TITLE
Status bar is not re-enabled on disposal

### ISSUE THREAD

**Issue by mcoolidge** [duytq94/flutter-intro-slider#49]
If hide status bar is enabled, this setting isn't reverted upon completion.

**Comment by duytq94** [comment]
Temporary you can fix it by

- Set shouldHideStatusBar = false
- Add `SystemChrome.setEnabledSystemUIOverlays([]);` at build function in main.dart (your intro page)
- Add `SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);` at build function in home.dart (your home page)

**Comment by mcoolidge** [comment]
Was this fixed? The workaround is fine, but not ideal.

**Comment by duytq94** [comment]
So did you have a better idea?
This case depends on Flutter logic, not depend on the plugin. When you hide the status bar at first screen and navigate to the second screen, you need to turn on it again.

**Comment by ameenbadri7** [comment]
SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
this fix my problem thanks.
