### ISSUE TITLE
onDonePress button isnt disabled on "null" callback

### ISSUE THREAD

**Issue by marcmarder** [duytq94/flutter-intro-slider#50]
The "Done" Button should be disabled if it receives a null callback. Currently that is missing.

> ` onDonePress: !isConnectedtoInet
                      ? null
                      : () {
                          if (_formKey.currentState.validate()) {
                            this.onDonePress();
                          }
                        }`

**Comment by marcmarder** [comment]
from Line 663:
```
// Done button
if (onDonePress == null) {
  onDonePress = () {};
}
```
could you remove that? It is completly ok to have a button with an null callback. If a button's callback is null it is rendered as disabled.

**Comment by duytq94** [comment]
OK, I'll close the issue since this behavior is normal.

**Comment by duytq94** [comment]
If you would like to hide done button, just set` isShowDoneBtn: false`.
Why you need the case that shows the button but does nothing or unclickable?
