### ISSUE TITLE
Customize description of slide 

### ISSUE THREAD

**Issue by ABINASH56** [duytq94/flutter-intro-slider#53]
How can I customize description of each slide

I want to add bulleted points and paragraphs in slides

**Comment by duytq94** [comment]
You can use this
![Screen Shot 2019-11-21 at 5 10 28 PM](https://user-images.githubusercontent.com/24253421/69328520-f3dec980-0c81-11ea-9bc9-a0fc330b3b78.png)

**Comment by ABINASH56** [comment]
please help me with a small example

`widgetDescription:`
