### ISSUE TITLE
Is it possible to use a slider children > child?

### ISSUE THREAD

**Issue by chelkaz** [duytq94/flutter-intro-slider#55]
I want 2 vertical blocks, the top column is a static image, and the bottom column is a slider
That the image would not move during a slide

Example:
```home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter layout demo'),
        ),
        body: Column(
          children: [
            Icon(Icons.star, color: Colors.green),
            IntroScreen(),
          ],
        )
      ),
```

**Comment by duytq94** [comment]
Yes, of course, you can set IntroScreen as a child of any widget.

**Comment by duytq94** [comment]
You can refer to this: https://github.com/duytq94/flutter-intro-slider/issues/56
