### ISSUE TITLE
i need to show two images in slider one i can show by path image but in other background image i cant give height width to it?

### ISSUE THREAD

**Issue by urvashikharecha** [duytq94/flutter-intro-slider#58]
i need to show two images in slider one i can show by path image but in other background image i cant give height width to it?
![Untitled-5](https://user-images.githubusercontent.com/20655150/71304214-b046bf00-23e9-11ea-9bbb-00ae61ade1fe.png)
want to show something like this please help?

**Comment by duytq94** [comment]
You can try https://github.com/duytq94/flutter-intro-slider#custom-your-own-tabs which you can pass your own custom tab to the slider.
