### ISSUE TITLE
Dispose tabController/animations

### ISSUE THREAD

**Issue by joknjokn** [duytq94/flutter-intro-slider#63]
Hi,

I some times get an error if I close the intro slider too soon. One or more tickers are not disposed. I guess you need to dispose the tabControllers and/or animations in the dispose call (which is not present at the moment).

Thank you for the plugin.

- Jonas

**Comment by duytq94** [comment]
Hi, what you mean close too soon at here, mean you navigate to another screen or something else?

**Comment by duytq94** [comment]
Fixed in https://github.com/duytq94/flutter-intro-slider/commit/ce12c150bc4ce636990717494e1266c9f9a28466
Feel free to let me know if the issue still exists.
Thanks.
