### ISSUE TITLE
Add button within the slide

### ISSUE THREAD

**Issue by johnareid54** [duytq94/flutter-intro-slider#64]
Is it possible to add a button to each slide after the description?
I wanted to add a button with the label "More" which would display a bottom sheet modal with additional text to explain in more detail the text shown on the slide.

**Comment by duytq94** [comment]
Yes, you can do it by set `widgetDescription`
![Screen Shot 2020-02-19 at 9 10 11 AM](https://user-images.githubusercontent.com/24253421/74795152-c55fa180-52f7-11ea-881c-a8ebd3441cf8.png)
Or custom entire tab through `listCustomTabs`

**Comment by johnareid54** [comment]
Thanks, Duy,
I put the following into my code (copied your example):
centerWidget: Text("Replace this with a custom widget", style: TextStyle(color: Colors.white)),
but it did not show up on the emulator, and the description was still shown.

**Comment by duytq94** [comment]
@johnareid54 `centerWidget` is the widget between title and description, it does not replace the description. If you use it, will show like this
![Screen Shot 2020-02-20 at 8 51 35 AM](https://user-images.githubusercontent.com/24253421/74893266-89434400-53be-11ea-8a1f-780cec42abfc.png)

**Comment by johnareid54** [comment]
Thanks, Duy,

It is mostlikely a fualt in my code. I am trying it on a new flutter blank app, using your example code. Unfortunately, my Macbook has  just forced me to update xcode to 11 and it is causing loads of problems and at the moment I cannot run flutter in debug mode. It might be a few days before it is back to normal.

**Comment by duytq94** [comment]
I'll close this issue since it depends on your code, btw feel free to discuss.
