### ISSUE TITLE
adding slides on the fly, how reset key?

### ISSUE THREAD

**Issue by Jan-pp** [duytq94/flutter-intro-slider#66]
I have a form on the third page and when this is filled out correctly a next slide should appear. Basically I'd like to be able to add a page, or just lock a page so the user can't get past slide 3 before want it to.

I tried just rebuilding the entire IntroSlider with an extra slide, but setState doesn't do anything... I think I need to give it a fresh key, but it is not possible to give IntroSlider a key...

Any suggestions?

**Comment by jacopofranza** [comment]
same problem, the widget does not respond to setState

**Comment by duytq94** [comment]
Now you guys can add key to make setState work
![Screen Shot 2022-09-22 at 5 38 49 PM](https://user-images.githubusercontent.com/24253421/191727292-0438e018-ee73-4927-9a80-9a534735af1a.png)
