### ISSUE TITLE
fullscreen with  shouldHideStatusBar: true

### ISSUE THREAD

**Issue by aemsoftwarearacatuba** [duytq94/flutter-intro-slider#69]
When checking the StatusBar: true parameter, the status bars did not show, but the image was not fullscreen. What can I do to adjust the image to fullsreen? Tks

**Comment by duytq94** [comment]
When you set `shouldHideStatusBar: true` the StatusBar will hide and then your image will fullsceen.

Check my Custom config example code for details.

![custom](https://user-images.githubusercontent.com/24253421/82004600-838f8e80-968d-11ea-884a-1373db63ab15.gif)
