### ISSUE TITLE
Is there the possibility to change the Buttons position from the bottom?

### ISSUE THREAD

**Issue by filippo-fresilli** [duytq94/flutter-intro-slider#73]
Hi, 
First of all thank you for your package. 
In my app I would like to set the "NEXT" button and the "SKIP" button (with all the dots) with more space from the bottom. Is there some method that can help me to do it?

Thank you in advance.

**Comment by duytq94** [comment]
Hi, at the moment it can't, may be I'll update in the future, e.g. support more dots like Instagram

**Comment by duytq94** [comment]
Implemented at version 4.0.0
https://github.com/duytq94/flutter-intro-slider#navigationbarconfig-parameter
