### ISSUE TITLE
Can i style the dot indicator movement animation?

### ISSUE THREAD

**Issue by Oladapo95** [duytq94/flutter-intro-slider#75]
Is it possible to style animation between the inactive dot and active dot.  Something like this.

![expanding-dot](https://user-images.githubusercontent.com/21201778/86420118-71b18b80-bccd-11ea-916e-ca52ee27743e.gif)

**Comment by duytq94** [comment]
Currently, this plugin doesn't support style the animation.

**Comment by pcmushthaq** [comment]
Is it possible to change the shape of the dot ? Maybe to square instead of round?

**Comment by duytq94** [comment]
Implemented at version 4.0.0
https://github.com/duytq94/flutter-intro-slider#indicatorconfig-parameter
Thanks!
