### ISSUE TITLE
bold description words

### ISSUE THREAD

**Issue by frederikw03** [duytq94/flutter-intro-slider#79]
is it possible to make some of the words in the description text bold? how would i do this 
like this:
![image](https://user-images.githubusercontent.com/58028622/87917742-b67f4580-ca75-11ea-9e70-0e96d2f05e87.png)

thanks

**Comment by duytq94** [comment]
Yes, you can use `widgetDescription` instead of `description` to make your custom widget then use
https://api.flutter.dev/flutter/widgets/RichText-class.html

**Comment by frederikw03** [comment]
I tried this but it dosent show up? i tried restarting too, but it did nothing
