### ISSUE TITLE
RTL languages support

### ISSUE THREAD

**Issue by abdallah-gaber** [duytq94/flutter-intro-slider#8]
Can You add the RTL languages support to slide and show the right directions for the widgets?

**Comment by duytq94** [comment]
[https://github.com/duytq94/flutter-intro-slider/pull/11](url)

**Comment by duytq94** [comment]
#11

**Comment by duytq94** [comment]
Hi @abdallah-gaber , I removed the RTL languages support, please read here to know more why we did it.
#20
