### ISSUE TITLE
RenderFlex overflow when there are allot of pages

### ISSUE THREAD

**Issue by dupiesdupreez** [duytq94/flutter-intro-slider#80]
![image](https://user-images.githubusercontent.com/6910085/88540431-362b8800-d013-11ea-9c60-7213d9505111.png)

The relevant error-causing widget was
    IntroSlider 
lib\…\screens\intro.dart:137
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

**Comment by dupiesdupreez** [comment]
I've remedied the problem by using the sizeDot property of the slider and making the dots smaller

**Comment by AlaaMarawi** [comment]
same problem ! but resizing the dots does not solve it.. it gives overflow error whenever dot number get bigger.
Hope this will be solved soon :)
