### ISSUE TITLE
Hide Done button until a condition

### ISSUE THREAD

**Issue by worthapenny** [duytq94/flutter-intro-slider#81]
Hey guys,

Quick question: Is it possible to hide the 'Done' button until some condition is true?

e.g. Hide or Disable the 'Done' button until a valid input.

**Comment by freppps** [comment]
Have the same question, i managed to almost solve it with following code:

`
@override
Widget build(BuildContext context)
{ return IntroSlider( slides: slides, renderDoneBtn: SizedBox(), ); }
`

The done button will be hidden but the area will still be clickable.
Would be nice if there is a way to completely get rid of the done button. i.e. make the area not clickable.

**Comment by duytran4** [comment]
Does `isShowDoneBtn` property help you guy?

**Comment by freppps** [comment]
I've totally missed that property. Worked perfect for me! Thanks @duytq94
