### ISSUE TITLE
check box don't show again 

### ISSUE THREAD

**Issue by adlucio87** [duytq94/flutter-intro-slider#83]
Hi guys,
thank you for your awesome packages.
Is it possible to add a checkbox into the slider?
I like to show the slider every time opening the app, then if checked don't show again i will hide it.
Thanks,
Andrea

**Comment by duytq94** [comment]
I think it's possible, just add checkbox widget to your slide, then use a local storage to write down user's option. Every time start your app, check this data to whether show or hide the slider.
