### ISSUE TITLE
feature request: ability to specify horizontal scroll physics

### ISSUE THREAD

**Issue by marchellodev** [duytq94/flutter-intro-slider#96]
It would be really neat to be able to assign horizontal scroll physics to `BouncingScrollPhysics `for example.

**Comment by duytq94** [comment]
I will add an attribute so you can set behavior for this action.

**Comment by duytq94** [comment]
Added at https://github.com/duytq94/flutter-intro-slider/releases/tag/2.3.4

**Comment by marchellodev** [comment]
Thanks!
