### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by mzdm** [duytq94/flutter-intro-slider#98]
Do you plan to add null safety support in the near future?

**Comment by duytq94** [comment]
Yes, I think will support it when this implementation officially release in Dart since I wait for it for a long time in Dart which I usually use in Kotlin.

**Comment by mzdm** [comment]
FYI null safety just hit stable. @duytq94

**Comment by xJon** [comment]
Would love to see it!

**Comment by quocbao238** [comment]
+

**Comment by antalmate12** [comment]
+1

**Comment by bartekpacia** [comment]
+1, can't wait to see null-safety in this lib!

**Comment by KabinManandhar** [comment]
@duytq94 just a friendly reminder to bump up the library with null safety support. :D

**Comment by David-DT** [comment]
I made a pr for it: https://github.com/duytq94/flutter-intro-slider/pull/102

**Comment by KabinManandhar** [comment]
> @duytq94 just a friendly reminder to bump up the library with null safety support. :D
I dont see it happening any sooner, I've switched to [https://pub.dev/packages/introduction_screen](url), you should to.

**Comment by moioo91120** [comment]
+1

**Comment by marchellodev** [comment]
+1

**Comment by sahmadreza** [comment]
+1

**Comment by duytq94** [comment]
Null safety version has release
https://github.com/duytq94/flutter-intro-slider/releases/tag/2.4.0
Thank you guys and @Tuditi for this PR https://github.com/duytq94/flutter-intro-slider/pull/102
