### ISSUE TITLE
smooth sliding

### ISSUE THREAD

**Issue by amervelic** [duytq94/flutter-intro-slider#99]
i use the same flutter app for desktop (macOS) and web but sliding is not as good as on macOS, it lags a lot

**Comment by LautaroLobo12** [comment]
That is because is not build for the web => it does not have web support. Yet. Hopefully we will have it someday.

**Comment by duytq94** [comment]
I temporary disabled using dart:io and tested with web then it runs normally, so I'll close this issue because just focus on this problem is enough
https://github.com/duytq94/flutter-intro-slider/issues/100#issuecomment-864514888
